import pandas as pd
csv_file = pd.read_csv("ip_list.csv")
print(type(csv_file))
print("=================================")
print(csv_file.dtypes)
print("=================================")
print(csv_file.shape )
print("=================================")
print(csv_file.describe( ))
print("=================================")
print(len(csv_file))
print("=================================")
print(len(csv_file.columns))
print("=================================")
print(csv_file['hostname'])
print("=================================")
print(csv_file["ips"])
print("=================================")
print(csv_file[["ips", "hostname"]])
print("=================================")
print(csv_file.iloc[1:3, 0:2])
print("=================================")
print(csv_file.iloc[0,1])
print("=================================")
print(csv_file.iloc[1])
print("=================================")
print(csv_file.iloc[:, 1])
print("=================================")
csv_file.to_csv("testcsv.csv")